# stage 1
# install node and dependencies
FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod
RUN npm install -g @angular/cli

# stage 2 
# install python and dependencies
# Update apt packages
RUN apt update
RUN apt upgrade -y

# Install submodule
RUN git submodule update --init --recursive

# Install vim
RUN apt install vim -y

# Install python 3
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3 -y

# Install pip
RUN apt install python3-pip -y
RUN python3 -m pip install --upgrade pip

# Install requirements
RUN pip3 install -r requirements.txt

#alas python3 as python
RUN alias python=python3

CMD ["npm", "start"]
